### ISSUE TITLE
Swapped columns with results on files page

### ISSUE THREAD

**Issue by xvitovs1** [mchalupa/benchexec-results-viewer#9]
The results on files page are probably not correctly ordered. When I choose e.g. `symbiotic-simple:SPIN-18.MemSafety-Arrays [2018-02-24 14:35:55]`  and `symbiotic-20:fs-debug.ReachSafety-Arrays [2018-02-27 18:30:04] ` the columns are swapped.

**Comment by mchalupa** [comment]
Is this fixed?
